ログイン画面とイベント作成完了画面
yanagimura/yeahcheese pull request #13
Opened 2018-04-17 08:54 UTC by yanagimura

セッション３つ分（'login', 'create','authSession')のリセット方法にバグがありました…。
各セッションをリセットしている画面のクラスを修正致しました。

2018-04-18 04:13 UTC, sen-higa requested changes
レビュー遅くなってすみません、、
以下気になった点です。

2018-04-18 04:13 UTC, sen-higa commented on training/app/action/Login.php
> +            unset($_SESSION['login']);
すみません、私がunsetで良いのではないかとお伝えしたので、こう書いてもらったのですが、
`$this->session->remove('login')`でも同じかと思います。
Ethna_Sessionに合わせてあげてください…:bow:
http://ethna.jp/api/2.5.0/Ethna/Ethna_Session.html#remove

2018-04-18 04:13 UTC, sen-higa commented on training/app/view/Upload.php
> +        unset($_SESSION['authSession']);
こちらも同様にお願いします:bow:
`$this->session->remove('create');`
`$this->session->remove('authSession');`

2018-04-18 04:13 UTC, sen-higa commented on training/template/ja_JP/home.tpl
> +    <a href="http://localhost:8000/?action_login=true">ログアウト</a>
こちらどうしてloginにしたのでしょうか？
Login.phpの`prepare()`にログインセッションが開始しているか判定してログアウトさせようとしている感じですか？
それだとちょっと紛らわしいので、Logout.phpでちゃんとログアウトした方がいいと思います。

2018-04-18 04:21 UTC, yanagimura commented on training/template/ja_JP/home.tpl
> +    <a href="http://localhost:8000/?action_login=true">ログアウト</a>
ご指摘ありがとうございます！ちょっと見直してみます汗

http://localhost:8000/?action_logout=trueを投げた後に、
Logout.phpでセッションをremove後、http://localhost:8000/?action_login=trueを表示
っていう流れでかいてみます！

2018-04-20 00:47 UTC, sen-higa requested changes
度々レビュー遅くてすみません、、
以下確認お願いします。

2018-04-20 00:47 UTC, sen-higa commented on training/app/view/Upload.php
> +        $this->session->remove('authSession');
最初に言えよって感じだと思うのですが、ここ必要ですかね？
action/Upload.phpにも同じ処理があるので、不要ではないかと思いました。

2018-04-20 00:47 UTC, sen-higa commented on training/app/action/Logout.php
> +        $this->session->remove('login');
特に理由がない限り、ログアウト時はdestroyしてしまっていいと思います。
ログアウトしてもセッションを破棄させたくないみたいな場合には認証状態だけクリアするということもあるみたいです。
(どんな状況なのかあんまりわからないですが…)

2018-04-20 05:51 UTC, sen-higa approved these changes
以下コメントです。
`$this->session->isStart()`は修正お願いします！

2018-04-20 05:51 UTC, sen-higa commented on training/app/action/Login.php
> +        if ($this->session->isStart('login')) {
`$this->session->isStart()`ですね。

2018-04-20 05:51 UTC, sen-higa commented on training/app/action/Login.php
> +            $this->session->remove('login');
こちら、すでにログイン済みということであればホーム画面(ログイン後画面)に遷移させてもいいのではないでしょうか？

2018-04-20 11:03 UTC, sen-higa approved these changes
OKですー！

2018-04-22 23:45 UTC, merged