登録画面用の再レビュー用
yanagimura/yeahcheese pull request #3
Opened 2018-04-11 06:28 UTC by yanagimura

以下のブランチでは、登録画面とログイン画面の両方のファイルがプッシュされている状態でした…。
https://github.com/yanagimura/yeahcheese/pull/2

このブランチには、登録画面のファイルのみプッシュしました。
昨日（４月１０日）にレビューを頂いた部分は改修済みです。

2018-04-11 08:13 UTC, FujimoriYuya commented on training/app/action/Register/Do.php
> +               'custom'      => 'checkDBAddress',    // Optional method name
`custom` 連結して書いた方がいいと思います。

```
'custom' => 'checkMailaddress, checkDBAddress'
```

2018-04-11 08:32 UTC, inukai-norio reviewed
コメントです。

2018-04-11 08:32 UTC, inukai-norio commented on training/app/action/Register/Do.php
> +     function checkPassword($password)
public アクセスなら、明示的に書いたほうがいいと思います。
以下同文

2018-04-11 08:32 UTC, inukai-norio commented on training/app/action/Register/Do.php
> +       if($this->form_vars[$password] !== $this->form_vars['password']){
これ、 結局 `$a !== $a` なので、常に `false` になるよ

2018-04-12 00:15 UTC, rymiyamoto commented on training/app/action/Register/Do.php
> +       if($this->form_vars[$password] !== $this->form_vars['password']){
ならなくね？
ここの$password は password_confirm カスタムチャックのやつだし

2018-04-12 02:45 UTC, sen-higa requested changes
以下、気になった点です！
あと全体的にですが、インデントがスペース2個分になっているかと思います。

PSR-2に従って、4スペースでお願いしますm(_ _)m
(設定によるかもですが、atomでは普通に改行すると2個分のインデントが付きます。タブ押したらさらに2個分追加してくれます！)

2018-04-12 02:45 UTC, sen-higa commented on training/app/action/Register/Do.php
> +     function checkPassword($password_confirm)
こちらもアクセス修飾子を付けてあげましょう。
`Sharepictures_Form_RegisterDo`クラス以外から呼ばれないのであれば、`private`でいいと思います。
```
public     // クラス内、クラス外のどこからでもアクセス可能
private    // 同じクラス内からのみアクセス可能
protected  // 同じクラス、及び子クラスからアクセス可能
```

2018-04-12 02:45 UTC, sen-higa commented on training/app/action/Register/Do.php
> +      $cipherpass = hash('sha256', $pass);
こう書いて上げると、`$pass`が不要になってスッキリするかと思いました。
```
$cipherpass = hash('sha256', $this->af->get('password'));
```

2018-04-12 04:05 UTC, sen-higa approved these changes
見逃していた所直していただければOKです！
`array()`の箇所を`[]`に変えたんですね👍

2018-04-12 04:05 UTC, sen-higa commented on training/app/action/Register/Do.php
> +               'custom'      => ['checkMailaddress', 'checkDBAddress'],   // Optional method name
見逃しで申し訳ありません、、書き方こうですね・・・
`'custom'  => 'checkMailaddress, checkDBAddress'`

2018-04-12 04:06 UTC, sen-higa commented
再レビュー依頼は不要でございますー

2018-04-12 06:27 UTC, yanagimura commented
ありがとうございます！

2018-04-12 07:01 UTC, merged